apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  # 메인 애플리케이션 컨테이너
  - name: main-app
    image: nginx:1.25
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-logs        # 볼륨 마운트
      mountPath: /var/log/nginx  # nginx 로그 경로
  
  # 사이드카 컨테이너 (로그 수집)
  - name: log-sidecar
    image: busybox:1.36
    # 로그 파일을 실시간으로 읽어서 출력
    command: ['sh', '-c', 'tail -F /var/log/nginx/access.log']
    volumeMounts:
    - name: shared-logs        # 같은 볼륨 마운트
      mountPath: /var/log/nginx
  
  # 공유 볼륨 정의
  volumes:
  - name: shared-logs
    emptyDir: {}               # Pod 수명과 같은 임시 볼륨