apiVersion: v1
kind: Pod
metadata:
  name: db-app-pod
spec:
  containers:
  - name: app
    image: nginx:1.25
    env:
    - name: DB_USERNAME            # Pod에서 사용할 변수 이름
      valueFrom:
        secretKeyRef:              # ⭐ Secret에서 가져옴
          name: db-secret          # Secret 이름
          key: username            # Secret의 키
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password